[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: testes essenciais de fumaca
    regression: testes de regressao completos
    pet: endpoints de pet
    store: endpoints de store
    user: endpoints de user
    negative: cenarios negativos
addopts =
    -v
    --tb=short
    --strict-markers
    --alluredir=allure-results
    --html=report.html
    --self-contained-html
